services:
  app:
    image: experiment-toolkit
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./public/experiments/${VITE_EXPERIMENT_ID}.json:/usr/share/nginx/html/experiments/${VITE_EXPERIMENT_ID}.json  # Automatically mount the config.json file