services:
  app:
    image: experiment-toolkit
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./public/config/experiments/${VITE_EXPERIMENT_ID}/config.json:/usr/share/nginx/html/config/experiments/${VITE_EXPERIMENT_ID}/config.json  # Automatically mount the config.json file